server.port: 8082
spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/youtube-video-player?serverTimezone=UTC
    username: youtube-video-player
    password: youtube-video-player

